LibraryMVC/Controllers/BookController.cs
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebModelService.BookModel;
using WebModelService.BookModel.Contracts.ViewModels;

namespace LibraryMVC.Controllers
{
    public class BookController : Controller
    {
        private IBookService bookService;

        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        public ActionResult Index()
        {
            return View();
        }

        //////// GET BOOKS //////////

        [HttpPost]
        public ActionResult GetBooks([DataSourceRequest] DataSourceRequest request)
        {           
            return Json(this.bookService.GetBooks().ToDataSourceResult(request));
        }

        ////////// CREATE ///////////

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView("Create");
        }

        // POST
        [HttpPost]
        public ActionResult Create(BookViewModelCreate book)
        {
            if (ModelState.IsValid)
            {
                this.bookService.AddBook(book);
                return Json(new { isDone = true });
            }
            else
            {
                return PartialView(book);
            }
        }

        ////////// EDIT ///////////

        [HttpGet]
        public ActionResult Edit(int id)
        {
            BookViewModelEdit viewModel = this.bookService.GetBookEdit(id);
            
            return PartialView("Edit", viewModel);
        }

        // POST
        [HttpPost]
        public ActionResult Edit(BookViewModelEdit book)
        {
            if (ModelState.IsValid)
            {
                this.bookService.EditBook(book);
                return Json(new { isDone = true });
            }
            else
            {
                return PartialView(book);
            }
        }

        ////////////    DETAILS     /////////////

        [HttpGet]
        public ActionResult Details(int id)
        {
            ViewBag.id = id;
            return PartialView("Details");
        }

        [HttpGet]
        public ActionResult DetailsStatus(int id)
        {
            return PartialView(this.bookService.GetBookDetailsStatus(id));
        }

        [HttpGet]
        public ActionResult DetailsHistory(int id)
        {
            return PartialView(this.bookService.GetBookDetailsHistory(id));
        }
    }
}

LibraryMVC/Controllers/BorrowController.cs
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebModelService.BorrowModel;
using WebModelService.BorrowModel.Contracts.ViewModels;

namespace LibraryMVC.Controllers
{

    public class BorrowController : Controller
    {
        private IBorrowService borrowService;

        public BorrowController(IBorrowService borrowService)
        {
            this.borrowService = borrowService;
        }

        // GET: Borrow
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult UsersIndex([DataSourceRequest] DataSourceRequest request)
        {
            return Json(this.borrowService.GetUsersList().ToDataSourceResult(request));
        }

        public JsonResult BooksIndex([DataSourceRequest] DataSourceRequest request)
        {
            return Json(this.borrowService.GetBooksList().ToDataSourceResult(request));
        }

        [HttpGet]
        public ActionResult Create(BorrowViewModelCreate borrow)
        {
            return PartialView("Create");
        }

        [HttpGet]
        public JsonResult GetTitles()
        {
            return Json(this.borrowService.GetTitlesList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetNames()
        {
            return Json(this.borrowService.GetNamesList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult BorrowBooks(BorrowViewModelCreate model)
        {
            this.borrowService.AddBorrow(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Return(int[] borrowId)
        {
            this.borrowService.ReturnBorrows(borrowId);
            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult ShowUserBooks(int id)
        {
            var model = this.borrowService.ShowUserBooksBorrow(id);
            return View("UserBooks", model);
        }
    }
}

LibraryMVC/Controllers/RaportController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebModelService.RaportModel;

namespace LibraryMVC.Controllers
{
    public class RaportController : Controller
    {
        private IRaportService raportService;

        public RaportController(IRaportService raportService)
        {
            this.raportService = raportService;
        }

        // GET: Raport Index View
        [HttpGet]
        public ActionResult Index()
        {
            return View("Index");
        }

        // GET: Users Index View
        [HttpGet]
        public ActionResult UsersRaportIndex()
        {
            var model = this.raportService.GetUsersRaport();
            return PartialView("UsersRaportIndex", model);
        }

        //GET: Books Index View
        [HttpGet]
        public ActionResult BooksRaportIndex()
        {
            var model = this.raportService.GetBooksRaport();
            return PartialView("BooksRaportIndex", model);
        }

        //GET: Books List
        [HttpGet]
        public JsonResult GetBooksRaport()
        {
            var query = this.raportService.GetBooksRaport();
            return Json(query, JsonRequestBehavior.AllowGet);
        }

        //POST: Books List
        [HttpPost]
        public JsonResult GetBooksRaport([DataSourceRequest] DataSourceRequest request, int? genre, string title, DateTime? fromDate, DateTime? toDate)
        {
            var query = this.raportService.GetFilteredBooksRaport(genre, title, fromDate, toDate).ToDataSourceResult(request);
            return Json(query);
        }

        //POST: Users List
        [HttpPost]
        public JsonResult GetUsersRaport([DataSourceRequest] DataSourceRequest request)
        {
            return Json(this.raportService.GetUsersRaport().ToDataSourceResult(request));
        }

        //GET: Genres List
        [HttpGet]
        public JsonResult GetGenresRaport()
        {
            return Json(this.raportService.GetGenresRaport(), JsonRequestBehavior.AllowGet);            
        }       
    }
}

LibraryMVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebModelService.UserModel;
using WebModelService.UserModel.Contracts.DTOs;
using WebModelService.UserModel.Contracts.ViewModels;

namespace LibraryMVC.Controllers
{
    public class UserController : Controller
    {
        private IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }
         
        //
        // GET: /User/

        public ActionResult Index()
        {
            return View(this.userService.GetUsers());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        public ActionResult Create(UserViewModelCreate user)
        {
            if (ModelState.IsValid)
            {
                this.userService.AddUser(user);
                return RedirectToAction("Index");
            }

            return View(user);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {                     
            UserViewModelEdit viewModel = this.userService.GetUserEdit(id);
            return View(viewModel);
        }

        //
        // POST: /User/Create

        [HttpPost]
        public ActionResult Edit(UserViewModelEdit user)
        {
            if (this.userService.EmailExist(user.UserId, user.Email))
            {
                ModelState.AddModelError("Email", "Email already in use");
            }

            if (ModelState.IsValid)
            {
                this.userService.EditUser(user);
                return RedirectToAction("Index");
            }

            return View(user);
        }

        [HttpGet]
        public ActionResult Delete(int id = 0)
        {
            UserViewModel usVM = this.userService.GetUser(id);
            return View(usVM);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            this.userService.DeleteUser(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DetailsActual(int id)
        {           
            return PartialView(this.userService.GetUserDetailsActual(id));
        }

        [HttpGet]
        public ActionResult DetailsHistory(int id)
        {
            return PartialView(this.userService.GetUserDetailsHistory(id));
        }
    }
}

LibraryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

	<!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
	@Scripts.Render("~/bundles/jquery")
	<link href="@Url.Content("~/Content/kendo/2016.2.607/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2016.2.607/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2016.2.607/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2016.2.607/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2016.2.607/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2016.2.607/jquery.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2016.2.607/jszip.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2016.2.607/kendo.all.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2016.2.607/kendo.aspnetmvc.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LIBRARY", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                    <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    <li>@Html.ActionLink("Borrows", "Index", "Borrow")</li>
                    <li>@Html.ActionLink("Raports", "Index", "Raport")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Library Application</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>